source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<esc><wait>", "<esc><wait>", "<enter><wait>", "/install/vmlinuz<wait>", " initrd=/install/initrd.gz", " auto-install/enable=true", " debconf/priority=critical", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>", " -- <wait>", "<enter><wait>"]
  boot_wait               = "20s"
  disk_size               = 20480
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "Ubuntu_64"
  headless                = false
  http_directory          = "http"
  iso_checksum            = "sha1:87bedd68607f059ca973f86346bbdf1caa6e1077"
  iso_url                 = "C:\\my-path\\vagrant-base\\vagrant\\files\\ubuntu-18.04.1-server-amd64.iso"
  output_directory        = "vagrant-ubuntu18-virtualbox"
  shutdown_command        = "echo 'vagrant'|sudo -S shutdown -P now"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "10000s"
  ssh_username            = "vagrant"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "1024"], ["modifyvm", "{{ .Name }}", "--cpus", "1"]]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "vm-vagrant-thebestproject-tmp"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/thebestproject-tmp.conf"
    source      = "files/thebestproject-tmp.conf"
  }

//  provisioner "file" {
//    destination = "/tmp/thebestproject-tmp.cert"
//    source      = "files/thebestproject-tmp.cert"
//  }
//
//  provisioner "file" {
//    destination = "/tmp/thebestproject-tmp.key"
//    source      = "files/thebestproject-tmp.key"
//  }

  provisioner "file" {
    destination = "/tmp/xdebug.ini"
    source      = "files/xdebug.ini"
  }

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'"
    script = "scripts/full.sh"
  }

  post-processor "vagrant" {
    output = "builds/thebestproject-tmp.box"
  }
}
